name: eezi_connect
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.1.9+1
  cloud_firestore: ^0.14.2
  cupertino_icons: ^1.0.0
  device_apps: ^1.2.0
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  firebase_storage: ^5.0.0
  flutter_screenutil: ^3.2.0
  flutter_facebook_auth: ^0.3.3
  get: ^3.15.0
  get_it: ^5.0.1
  get_storage: ^1.3.2
  google_fonts: ^1.1.1
  google_sign_in: ^4.5.5
  http: ^0.12.2
  injectable: ^1.0.5
  loading_overlay: ^0.2.1
  path_provider: ^1.6.22
  pin_code_fields: ^6.0.0
  pin_input_text_field: ^3.1.1
  stacked: ^1.7.6
  url_launcher: ^5.7.8
  cached_network_image: ^2.3.3
  image_picker: ^0.6.7+12
  photo_view: ^0.10.2
  #  Push Notif
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.1+2
  permission_handler: ^5.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  injectable_generator: ^1.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue-VariableFont_wght.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
